[telegram]
# Get your API ID/HASH from https://my.telegram.org/auth

phone_number="+447859849598"
api_id=24429280
api_hash="8cb5d414cefbad16c6bf85a43dad8d62"

[sending]
# The send interval is how long you want to wait between sending messages.
# The loop interval is how long you want to wait before re-sending messages to all the groups.

send_interval=15
loop_interval=3600